### ISSUE TITLE
Solana Moonzoon Connection

### ISSUE THREAD

**Issue by buildgreatthings** [MartinKavik/voting-anchor-moonzoon#2]
When I start the Monsoon front end, the Solana connection doesn't work. I can verify my Solana test cluster through CLI and visiting `http://localhost:8899`

```
% ./mzoon start -o
Start { release: false, open: true }
Building frontend...
    Finished dev [unoptimized + debuginfo] target(s) in 0.43s
[WARN]: ⚠️   There's a newer version of wasm-pack available, the new version is: 0.10.2, you are using: 0.10.1. To update, navigate to: https://rustwasm.github.io/wasm-pack/installer/
Frontend built
Building backend...
    Finished dev [unoptimized + debuginfo] target(s) in 0.56s
Backend built
Run backend
Open http://localhost:8080 in the default web browser
voting_state_pubkey: 4MPyVsUgCHHmapxrGNA79MZZtaciEUiLGCvusdDQfmqU
thread 'tokio-runtime-worker' panicked at 'get_recent_blockhash failed: ClientError { request: Some(GetLatestBlockhash), kind: RpcError(RpcResponseError { code: -32601, message: "Method not found", data: Empty }) }', backend/src/solana_helpers.rs:67:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'get_recent_blockhash task failed: JoinError::Panic(...)', backend/src/solana_helpers.rs:70:6
```

**Comment by MartinKavik** [comment]
This project is WIP and I'm not sure I'll finish it. I've written a warning in the readme but perhaps it's easy to overlook it.

I would suggest to look at the working (I hope it still works) raw Solana example: https://github.com/MartinKavik/voting-solana-moonzoon or pick another project if you want to learn only Anchor.
